### ISSUE TITLE
Submission model

### ISSUE THREAD

**Issue by pepyta** [pepyta/sygnmnt#34]
Submission model:
```
id String @id @default(uuid())
createdAt Date @defalt(now())
status Status
files File[]
user User
task Task

userid String
taskid String
```

Status: `RUNNING` / `SUCCESS` / `FAILED`

Question: What else could we include in this model?

**Comment by 2976579765** [comment]
An additional ```message``` string should also be stored, as the status enum itself would not be sufficient for storing a failed test's output. Maybe let the backend test submissions on a timely basis - because tests wouldn't be ran after submission immediately (or in case automatic grading is not possible at all), status could also have an `UPLOADED` constant. If we let owners or aux give feedback manually, they (their user account) should also be stored - this could help the submitter contact them if needed.
Related issue: #31

**Comment by pepyta** [comment]
@2976579765 We are storing complete log history for each submission, so the student can look back what was the last issue. Also, we can't simply determine what was real issue as we only have a string stream from Docker and no internal access to the build/run process.

You are right about the UPLOADED status, I will update that
